README.md

test fork and pull into master

---

hdbscan/hdbscan_.py

Fixes the performance on `cosine` metric

---

hdbscan/_hdbscan_boruvka.pyx
hdbscan/_hdbscan_linkage.pyx
hdbscan/_hdbscan_reachability.pyx
hdbscan/_hdbscan_tree.pyx
hdbscan/dist_metrics.pyx
hdbscan/hdbscan_.py
hdbscan/robust_single_linkage_.py
hdbscan/tests/test_hdbscan.py
hdbscan/tests/test_rsl.py

[MRG] Address issue #61 - PEP8

---

docs/parameter_selection.rst

It was hard to read in the docs, and as it actually is Python code, I thought this is what you actually wanted.

Add missing code block marker

---

paper/paper.md

minor fixes

---

docs/basic_hdbscan.rst
docs/faq.rst
docs/how_hdbscan_works.rst

As I read through the docs, I made some fixes of minor typos. 
Thank you!

Some minor typos and grammer

---

hdbscan/plots.py

Should fix #151 , but I'm struggling with running tests on Win machine (the known "ERROR: Failure: ImportError (No module named _hdbscan_linkage)").

Fix for fix for issue #151

---

docs/advanced_hdbscan.rst

Fixed some misspelled words and wrong commas. Also introduced the canonical spellings of NumPy and NetworkX.

Clean up spelling in advanced_hdbscan.rst

---

setup.py

* Include the tests with the package so that they can be run after installation with:
`nosetests -s hdbscan`
or
`python -m nose -s hdbscan`
* Increment debug revision counter since this does add a feature to the release.
Using the 'rc' version tag because I'm not sure if there's anything else we want to change before release.
Alternatively, I have read that we can add the 'post' version tag, e.g., `0.8.12post1`

Include Tests for Distributing Wheels

---

README.rst

Adding information about running the tests after installation.

Document Test Procedure

---

README.rst

Sorry, I missed some things. Moving last sentence into the correct place. Fixing markdown syntax for code styling.

Edits to README.rst

---

README.rst

A simple bug in sample code I stumbled upon while testing the package. The first code sample seems to have already been sorted a while ago, so this fix is for the second one.

fixing code sample

---

docs/parameter_selection.rst

note parameters that result in hard computation

---

docs/comparing_clustering_algorithms.rst

A bullet-point list was mistyped and showed on only one line.

Fixed markup typo

---

docs/basic_hdbscan.rst

I've asked a question on stack overflow that led me to this comment update. https://stackoverflow.com/questions/53808957/how-do-i-use-sklearn-metrics-pairwise-pairwise-distances-with-callable-metric
I hope it provides others useful information if they stumble across the same thing.

Clarify that inputs to HDBSCAN must be numeric

---

hdbscan/plots.py

As also noted in issue [#94](https://github.com/scikit-learn-contrib/hdbscan/issues/94) lambda can go to infinity. If this happens, plotting the condensed tree with `select_clusters=True` will silently suppress the ellipse around the cluster. Setting `label_clusters=True` will raise an error in this case.
I made the following changes,
- Issue a warning if infinite lambda values are encountered
- Set a default center and height value for ellipses highlighting the chosen cluster if lambda is infinite
- Having an extremely dense cluster (or a large imbalance in cluster size) might further result in ellipses which are barely visible for the less dense/small clusters. I included a check to set a min value to ensure all ellipses are at least `min_height` tall.
This probably isn't perfect but …

Improve handling of infinite lambda values

---

requirements.txt

Fix according to https://github.com/scikit-learn-contrib/hdbscan/issues/272

fixed the numpy version

---

hdbscan/prediction.py

Additional fix for #231, the same way as in https://github.com/scikit-learn-contrib/hdbscan/commit/0800b0bb1a643d6d09029a0742f2a1c22146f7b1

Simple additional fix for #231

---

hdbscan/_hdbscan_tree.pyx
hdbscan/hdbscan_.py

Added an optional parameter epsilon, for details please see "HDBSCAN(ε^): An Alternative Cluster Extraction Method for HDBSCAN", https://arxiv.org/abs/1911.02282 
If epsilon is None or 0, results will be exactly the same as the original HDBSCAN. 
For epsilon > 0, clusters will be merged up to distance epsilon.

add epsilon parameter to merge clusters based on distance

---

hdbscan/tests/test_hdbscan.py

Not sure if you prefer comparing to the exact expected output or using assert_array_almost_equal where almost equal is within 1 decimal place

Add unit test for cluster centroids/medoids

---

setup.py

Release that fixes bug with weighted_cluster_medoid
https://github.com/scikit-learn-contrib/hdbscan/issues/353

Release fix for #353

---

hdbscan/_hdbscan_boruvka.pyx

Fix the core distance computation can only use 4 cores. 
Issue #310
Close #310

fix the core distance computation can only use 4 cores.

---

hdbscan/_hdbscan_tree.pyx
hdbscan/tests/test_hdbscan.py

fixes issue #417 
This is rebased onto pull request #400 since I have not completed that merge yet (so ignore _hdbscan_tree.pyx:744-752). I will rebase this to master when 400 is complete.

let root children size==1 to join root node in allow_single based on 1/eps

---

hdbscan/hdbscan_.py

Fix typo in docstring

---

.readthedocs.yaml
docs/docs_requirements.txt

Hi @lmcinnes , this can fix the issue of read the docs running failure, please have a look. Thanks.

Add .readthedocs.yaml to fix failing docs build issue.
