scikit-learn-contrib/hdbscan

- setup.py
Just a small change that sets the `HAVE_CYTHON` flag to `False` in case it is not installed on the end user's machine.
> Add HAVE_CYTHON flag in case Cython is not installed

- README.rst
Fixed broken link in README – it's a tiny contribution, but a contribution nonetheless :)
> Fixed README.rst link to "Python vs Java"-notebook in nbviewer

- hdbscan/hdbscan_.py
Hey,
First of all, nice toolbox. I was playing yesterday with it and I was using the number of core in the same way than in sklearn but negative numbers of CPU raised some errors.
That's why, I proposing a change as implemented in sklearn.
Let me know if you are interested about that.
Cheers,
> [MRG] Handle negative n_jobs as in sklearn

- setup.py
In Python 3 `pip install hdbscan` fails if Cython is not available:
```
pip install hdbscan
Collecting hdbscan
Downloading hdbscan-0.8.2.tar.gz (3.6MB)
100% |████████████████████████████████| 3.6MB 307kB/s 
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "/private/var/folders/_5/cbsg50991szfp1r9nwxpx8580000gn/T/pip-build-t3mz0asu/hdbscan/setup.py", line 4, in <module>
from Cython.Distutils import build_ext
ImportError: No module named 'Cython'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/private/var/folders/_5/cbsg50991szfp1r9nwxpx8580000gn/T/pip-build-t3mz0asu/hdbscan/setup.py", line 8, in <module>
warnings.warn(e.message)
AttributeError: …
```
> PY3 fixed installation without Cython

- hdbscan/tests/test_hdbscan.py
Added the following test:
```
def test_hdbscan_min_cluster_size():
for min_cluster_size in range(2, len(X)+1, 1):
labels, p, persist, ctree, ltree, mtree = hdbscan(X, min_cluster_size=min_cluster_size)
true_labels = filter(lambda label: label != -1, labels)
if len(true_labels) != 0:
assert_greater_equal(np.min(np.bincount(true_labels)), min_cluster_size)
labels = HDBSCAN(min_cluster_size=min_cluster_size).fit(X).labels_
true_labels = filter(lambda label: label != -1, labels)
if len(true_labels) != 0:
assert_greater_equal(np.min(np.bincount(true_labels)), min_cluster_size)
```
> Added test_min_cluster_size

- docs/parameter_selection.rst
Also replacing a small case `hdbscan` with `HDBSCAN\*` (even so I'm not sure what the asterisk is for).
> Fixing a few typos

- docs/advanced_hdbscan.rst
- docs/how_hdbscan_works.rst
Simple fixes to spelling mistakes. 
- advanced_hdbscan.rst : 'he' to 'the, line 219
- how_hdbscan_works.rst : 'and' to 'an', line 162
> Fix spelling mistakes in advanced_hdbscan.rst & how_hdbscan_works.rst

- hdbscan/plots.py
It looks like the order of arguments changes between [1.9](https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.classes.function.set_node_attributes.html) than [2.0](https://networkx.github.io/documentation/networkx-2.0/reference/generated/networkx.classes.function.set_node_attributes.html).
Since the networkx version 1.9 isn't specified in requirements.txt, I think it should reflect the newest version.
> switch order of arguments in networkx::set_node_attributes

- hdbscan/robust_single_linkage_.py
Tree was of type SingleLinkageTree. Now dereferenced to ndarray with class method.
> Fix #138, wrong return type in robust_single_linkage

- setup.py
If you ran `pip install hdbscan` in an empty virtual environment, you would get in error when setup.py tried to import numpy.
Adding this custom wrapper around build_ext will make it so numpy is installed first. Then the installation process can use it for the rest of the installation of hdbscan.
This method is credit to R_Beagrie's SO answer: https://stackoverflow.com/a/42163080
> Does not need numpy installed before installing hdbscan

- hdbscan/prediction.py
- hdbscan/tests/test_hdbscan.py
When no clusters found, return array of 0's from all_points_membership_vectors.
Test added. All tests passing.
> Fix for #157

- hdbscan/dist_metrics.pxd
- hdbscan/dist_metrics.pyx
A simple (possible) fix for #153, add `import`s and remove the `with gil` statement.
Compiles with Cython 0.27.3 (current as of today).
> Possible fix for #153

- hdbscan/_prediction_utils.pyx
Small fix in exponentiating the results in outlier computations removes the warnings about overflows (see for example https://github.com/scikit-learn-contrib/hdbscan/issues/161) and should also improve the accuracy in border cases.
There are couple other places where you have `result[i] = np.exp(1.0 / vector[i])`, which I guess might still cause overflow if `vector[i]`is very small, and where you could use log-sum-exp trick as well. I didn't touch these yet though.
> Improved numerical stability with exp

- hdbscan/hdbscan_.py
This is a first attempt to allow entries in a precomputed distance matrix to be undefined by setting them to `numpy.inf` (#187). The only necessary change seemed to be handling the input validation separately for the case `metric == 'precomputed'`and using `numpy.inf` instead of `numpy.nan` to not mess with the sorting, comparing and dividing in down-stream computations.  
I have attempted a workaround for the input validation by adding `check_precomputed_distance_matrix(X)` that executes the same checks as `check_matrix(X)` but allows for `numpy.inf`entries. Please check if that is clean enough for your taste and if `hdbscan_.py` is the place you would leave that function in.  
Something else that I couldn't reliably judge is if copying the `distance_matrix` in line 78 is necessary or …
> allow np.inf for missing values in case of precomputed metric

- docs/basic_hdbscan.rst
Finally delivering some minimal documentation for the support of missing distances in the precomputed metric case (#189).
I'm uncertain whether the bit about the path of defined distances between two points makes sense without explicitly mentioning the MST, but the context of the "Basic HDBSCAN" doc page suggested a minimally technical explanation.  
Feel free to help me find the right balance of jargon and ease of use.
Also, @lmcinnes, are there other places you would like to see information about the missing distances support? Like for example the `fit()` and `fit_predict()` docstrings?
> add doc for missing distances support

- pyproject.toml
As of [v10 of `pip`](https://pip.pypa.io/en/stable/reference/pip/#pep-518-support) [PEP 518](https://www.python.org/dev/peps/pep-0518/) is supported.  This allows for a `pyproject.toml` file to be created that specifies any build-system  requirements that need to be installed *before* the `setup.py` file is  run.  This solves the issue with pip needing `cython` and `numpy` before they are installed.
This has the added benefit that any packages that include this one as a `requirement` don't need to make sure `cython` is installed first (I am currently running into this issue with the package I am writing).
This has been tested with the command `pip install .` in clean python  environments in both python 3.6 and 3.7.  Pip was able to install the package and all dependencies in the correct …
> Add pyporject.toml file to specify build-system requirements

- MANIFEST.in
- setup.py
pyproject.toml needs to be included in the sdist tarball in order to have an effect.
> Add pyproject.toml to MANIFEST.in

- setup.py
Previously `requirements.txt` and `setup.py` listed different versions of packages and `setup.py` was missing the `scipy` dependency. This likely contributes to users' installation issues and the need for complex installation instructions.
This commit reads the package requirements directly from `requirements.txt` for both reduced maintenance and safer installation.
> Read setup.py dependencies from requirements.txt

- README.rst
With some of the packaging issues fixed the installation instructions can be simplified.
In particular, `pyproject.toml` and fixed `setup.py` mean that a simple `pip install hdbscan` is now enough, assuming the user has a relatively recent `pip`. Note that the default pip on many versions of Python is pip 8, which is too old. Pip does bug to be updated, but many users do not do that. Hence there is a note that if there is an issue to first upgrade pip then try again.
Another feature of pip is that it can pull directly from GitHub. This can be useful if a new feature is merged but not yet pushed to PyPI. The one-liner pip install is more convenient than manual download and installation.
> Clarify installation instructions

- hdbscan/hdbscan_.py
Implemented a fast approximation of the density based cluster
validity score. See relevant discussion here:
https://github.com/scikit-learn-contrib/hdbscan/issues/197
A fast approximation of the Density Based Cluster Validity (DBCV)
score. The only difference, and the speed, comes from the fact
that this relative_validity_ is computed using the mutual-
reachability minimum spanning tree, i.e. minimum_spanning_tree_,
instead of the all-points minimum spanning tree used in the
reference. This score might not be an objective measure of the
goodness of clustering. It may only be used to compare results
across different choices of hyper-parameters, therefore is only a
relative score.
Please advise on suitable test cases if required.
> Added relative_validity_ score as an attribute in HDBSCAN class

- hdbscan/plots.py
This only happens when a single cluster is returned, and when using the `"leaf"` argument for the clustering.
The result of `condensed_tree['parent'].min()` is an integer, but the output of the `_get_leaves` function should be a list, otherwise a `TypeError` can be raised.
For instance in `predictions.py`, with `list(selected_cluster)`:
```python
selected_clusters = condensed_tree._select_clusters()
self.cluster_map = {c: n for n, c in enumerate(sorted(list(selected_clusters)))}
```
and  `_select_clusters()` is a method of `CondensedTree` defined in `plots.py`, which calls `_get_leaves`
```python
def _select_clusters(self):
[ ... ]
elif self.cluster_selection_method == 'leaf':
return _get_leaves(self._raw_tree)
```
> Wraps output of condensed_tree's minimum in a list

- hdbscan/tests/test_rsl.py
test_rsl_high_dimensional fails as it uses a deprecated way of passing args to the metric, updated to use metric_params
> fix inorrect passing of arg to metric

- hdbscan/_hdbscan_reachability.pyx
- hdbscan/hdbscan_.py
This adds support for the alpha parameter in the same way it is done for dense matrices.
The change seems obvious so I'm not sure if there is a reason alpha support was missing? Are there fundamental problems using it in the sparse code path?
> Add alpha parameter to sparse distance matrices

- hdbscan/__init__.py
- hdbscan/hdbscan_.py
- hdbscan/robust_single_linkage_.py
- hdbscan/tests/test_hdbscan.py
- hdbscan/tests/test_rsl.py
- hdbscan/utils.py
- requirements.txt
I understand if this PR is rejected, I just wanted to get the ball rolling as we have to pin scikit-learn to <0.21 for hdbscan alone currently.
scikit-learn gives deprecation warnings about sklearn.externals.joblib being removed by 0.23. As far as I can tell they have also removed sklearn.externals.joblib.parallel by 0.21, so this import fails. Recent versions of scikit-learn depend on joblib, but older versions do not. You could solve this with a conditional install, or just always use joblib. I went for the latter solution.
As far as I can tell, they have also removed the convenience function if_matplotlib.
My changes are:
- Create .utils with if_matplotlib since the function is easily self-contained
- Add joblib to dependencies and move all imports from sklearn.externals.joblib to …
> fix import errors for scikit-learn 0.21

- hdbscan/_hdbscan_boruvka.pyx
- hdbscan/hdbscan_.py
- hdbscan/robust_single_linkage_.py
- requirements.txt
This PR addresses https://github.com/scikit-learn-contrib/hdbscan/issues/322.
When `hdbscan` is imported, the following `DuplicationWarning` is raised because `sklearn` will drop `six` and `joblib` from `externals` in the future version (0.2.3).
Importing those libraries directory circumvents the problem.
* Add `six` to `requirements.txt`.
* Substitute import statements in `hdbscan/_hdbscan_boruvka.pyx`, `hdbscan/hdbscan_.py`,  and `hdbscan/robust_single_linkage_.py`.
> Fix `DuplicationWarning` by importing the original libraries.

- hdbscan/hdbscan_.py
Sorry for yet another pull request - we decided to change the title of our paper about the epsilon cluster selection method to make it better citable (i.e., without any special characters). Therefore, I updated the title in the documented references in hdbscan_.py accordingly.
By the way, I noticed that the documentation is online now, but for some reason the last three images are not being displayed?
Thank you,
Claudia
> updated reference to epsilon cluster selection paper

- docs/faq.rst
This fixes the references to parameter selection sections in the FAQ.
> docs/faq.rst: Fix references

- hdbscan/dist_metrics.pyx
This is a fix for #348 
It is a quite simple fix of a typo in the code. I modified line 1076 in dist_metrics.pyx file from:
```
return acos(1.0 - d / sqrt(norm1 * norm2)) / M_PI
```
to this
```
return acos(d / sqrt(norm1 * norm2)) / M_PI
```
> #384 fixed error in arccos metric formula

- hdbscan/hdbscan_.py
Fix for https://github.com/scikit-learn-contrib/hdbscan/issues/353
> Change weighted_cluster_medoid to use argmin (not argmax)

- hdbscan/plots.py
Set the axis attribute of plt.colorbar so that when using the plotting function with passed subplot axes, the colourbar is placed on the correct subplot.
> Added axis control on colourbars

- hdbscan/__init__.py
- hdbscan/_hdbscan_tree.pyx
- hdbscan/prediction.py
- hdbscan/tests/test_hdbscan.py
I've added a small piece of code to generate predicted scores on new samples.
Also a fix is made in function _max_lambdas_ as the last computed value was never assigned to the returned array.
The code is modeled after the _outlier_score_ function, and uses the nearest neighbor to determine the parent node. One of my design goals for the code was having the same predicted score on the training dataset as the _outlier_scores__ attribute.
Attached is also a script to plot the values of the score on various toys dataset ("inspired" by the one in sklearn docs). The current implementation leads to very sharp edges, which is a bit counter-intuitive and might be a sign that something is not yet done properly. 
[plot_predict_scores.txt](https://github.com/scikit-learn-contrib/hdbscan/files/4495390/ …
> Predict score

- hdbscan/_hdbscan_tree.pyx
It seems like we want to disallow root from being present in the eom_clusters list. I am not sure if this adversely affects the underlying algorithm, but I poured over the code and it appears that the root cannot have a lambda value? Therefore it could not be considered in the epsilon search function.
> fix issue 370

- hdbscan/plots.py
This code replaces a lookup of the line widths with a tree traversal and fixes #390.
> Fixed line widths for single linkage dendrograms with duplicate lambda_val

- hdbscan/_hdbscan_boruvka.pyx
This patch makes several bugfixes and improvements to the union-find data
structure implemented by the BoruvkaUnionFind class:
(1) union_() did not update is_component.  If it merged two components
and no subsequent find() operation updated is_component, then
components() would report an incorrect result.
(2) Formerly, union_() did not recognize when it was passed two objects
in the same set.  In this case, it would improperly increment the set's
rank.  As a result, later calls to union_() sometimes produced unbalanced
trees, degrading performance.
(3) The path compression algorithm in find() has been replaced by Tarjan
and Van Leeuwen's path splitting algorithm.  Path splitting has the same
asymptotic performance as path compression, but it has better constant
factors because it requires …
> Improved union-find data structure implementation

- hdbscan/_hdbscan_tree.pyx
implemented discussion with @cmalzer https://github.com/scikit-learn-contrib/hdbscan/issues/370#issuecomment-649306255
fixes example code originally provided by @danielzgtg
epsilon search was working with allow_single_cluster except in the case where eom_clusters contained the root node, which was passed in as a leaf. 
Now if using 'eom', 'allow_single_cluster', and 'cluster_selection_epsilon' , the root node is returned as the selected cluster if it is the only cluster in the eom_clusters list.
> fixes #370 -- epsilon search would crash when root node in leaf list

- hdbscan/_hdbscan_boruvka.pyx
fix issue-436
joblib feature deprecated in joblib release 1.0.0 was causing crash
> fix issue-436 unused deprecated joblib option

- .travis.yml
- hdbscan/tests/test_flat.py
- hdbscan/tests/test_hdbscan.py
- hdbscan/tests/test_rsl.py
Closes #448:
* Drop Python 3.5 support (scikit-learn requires at least 3.6)
* Fix bugs in tests (use of removed testing utilities from sklearn, warnings filter)
> Fix build errors

- docs/comparing_clustering_algorithms.rst
From "...needs to conservative in int's clustering;" to "needs to be conservative in its clustering;"
> Fixing typos in "Don't be wrong!" section

- pyproject.toml
Use oldest-supported-numpy as build requirement to fix issue #457
> Update pyproject.toml to use oldest-supported-numpy

- hdbscan/_hdbscan_boruvka.pyx
- hdbscan/_hdbscan_tree.pyx
- hdbscan/flat.py
- hdbscan/prediction.py
This PR tries to fix a set of deprecation warnings thrown when hdbscan runs with numpy 1.20:
```
DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
```
Because of the way the test suite checks the warning stack, these deprecation warnings cause test failures against numpy==1.20
```
python3.8-hdbscan> E           AssertionError: assert False
python3.8-hdbscan> E            +  where False = issubclass(<class 'DeprecationWarning'>, UserWarning)
python3.8-hdbscan> E            + …
```
> Fix numpy 1.20 deprecation warnings

- hdbscan/hdbscan_.py
- hdbscan/robust_single_linkage_.py
- requirements.txt
This PR removes the usage of `six` from the package - mainly `six.string_types`. After the usage is removed, `six` is also removed from the requirements file.
> Remove usage of six

- docs/dbscan_from_hdbscan.rst
- docs/index.rst
- hdbscan/hdbscan_.py
- hdbscan/tests/test_hdbscan.py
Added a convenience wrapper function on our hdbscan object to easily extract a flat DBSCAN clustering at any epsilon value from our hdbscan run.  I also added some documentation to our read the docs page to describe this functionality.
> dbscan cluster extraction

- hdbscan/hdbscan_.py
Both attributes like min_samples and min_cluster_size can be defined
using other types of integer like Numpy's int16, int32 and int64. This
should be also supported by HDBSCAN. This commit only extendes the check
to other types of integers.
For further example, you can test using:
```python
import numpy as np
a = 10
b = np.int16(10)
c = np.int64(10)
print(isinstance(a, int))
print(isinstance(b, int))
print(isinstance(c, int))
print(np.issubdtype(type(a), np.integer))
print(np.issubdtype(type(b), np.integer))
print(np.issubdtype(type(c), np.integer))
```
The output is:
```bash
True
False
False
True
True
True
```
Signed-off-by: Julio Faracco <jcfaracco@gmail.com>
> hdbscan: add support to other types of input integers

- README.rst
- hdbscan/validity.py
While writing my Bachelor's Thesis which includes a comparison of clustering validity metrics like the one presented in [this paper](https://www.semanticscholar.org/paper/Relative-clustering-validity-criteria%3A-A-overview-Vendramin-Campello/ad93d3b55fb94827c4df45e9fc67c55a7d90d00b) (but focused on the application of metrics on non-spherical/density-based clusters) I noticed that DBCV actually performs better (according to my benchmarks, which only account for clusters with points that are normally distributed and lie relatively close to each other, especially in the case of non-spherical clusters) if it just used euclidean distances instead of mutual reachability distances when constructing the minimum spanning trees.
(the approach of the paper referenced above is also used in the DBCV …
> Add parameter to DBCV which toggles the usage of mutual reachability distances

- hdbscan/validity.py
Previously, `all_points_core_distance` would return NaN if all points within a cluster had a distance of zero to one another, i.e. were all the same. Now, if this case occurs, it returns an array of zeros with length `len(distance_matrix)`.
This PR is based on [this issue](https://github.com/scikit-learn-contrib/hdbscan/issues/127).
> Fixed: validity index no longer returning nan

- docs/basic_hdbscan.rst
- docs/how_hdbscan_works.rst
- hdbscan/hdbscan_.py
- hdbscan/robust_single_linkage_.py
The goal is to fix issue #562 by simply calling the joblib ``Memory`` class with a positional argument instead of explciitly using the (now deprecated) keyword name ``cachedir``.
> Use a positional argument for the cachedir/location

- .github/workflows/pythonpublish_wheel.yml
In light of the recent issues caused by compilation not working in various environments, I've created a github action to create and publish wheels for all operating systems and currently supported python versions.
The current publish job fails to upload a wheel because it's not compliant with the manylinux standards and PyPi won't accept distribution specific wheels. To get around this, I used the pypa official container for manylinux builds
For windows and osx the job is a copy of the other existing one, with the added matrix strategy to cover the combinations.
The wheels are created using non-isolated builds, so build requirements can be pinned if needed.
It is currently set to skip existing uploads in pypi, otherwise each job after the first one will report a failure just because the …
> Wheel publish github action

- hdbscan/hdbscan_.py
Fixes ```DeprecationWarning: `alltrue` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `all` instead.```
> Fixed DeprecationWarning in hdbscan/hdbscan_.py

- docs/parameter_selection.rst
> Typo fix in docs/parameter_selection.rst

- docs/how_to_use_epsilon.rst
Variable declaration typo in code block that will error if copy-pasting the code example
> correct typo in variable declaration

- .github/workflows/pythonpublish_wheel.yml
- azure-pipelines.yml
- hdbscan/_hdbscan_linkage.pyx
- hdbscan/_hdbscan_reachability.pyx
- hdbscan/_hdbscan_tree.pyx
- hdbscan/plots.py
- hdbscan/prediction.py
- hdbscan/validity.py
- pyproject.toml
This adds NumPy support, and for good sport also 3.12 wheels.  I didn't bother with supporting 3.8 (which NumPy 2 doesn't support) for wheels, since scikit-learn doesn't either anymore and you can use old wheels.
Tests pass locally, and will run with NumPy 2 now anyway, I presume (not that there are many).
> MAINT: Support NumPy 2 and build Python 3.12 wheels

- requirements.txt
Cython is a build-only dependency, so this PR removes Cython from the `install_requires` list of the hdbscan package.
[setup.py reads requirements.txt](https://github.com/scikit-learn-contrib/hdbscan/blob/master/setup.py#L78) to populate its runtime requirements, and [requirements.txt incldues cython](https://github.com/scikit-learn-contrib/hdbscan/blob/master/requirements.txt). So removing it from `requirements.txt` should be sufficient to fix this.
I can make a separate `requirements-build.txt` if the maintainers prefer using a requirements file for build dependencies.
> Remove cython from install requires

- hdbscan/hdbscan_.py
Setting ``min_samples`` to None, then ``min_samples`` should be equal to ``min_cluster_size`` .
This request is to modify the parameter descriptions of ``min_samples``, to ensure the HDSBCAN's documentation is aligned with parameter descriptions in https://scikit-learn.org/stable/modules/generated/sklearn.cluster.HDBSCAN.html#sklearn.cluster.HDBSCAN.
Thanks
> Modify description of ``min_samples``

- docs/how_to_detect_branches.rst
- hdbscan/plots.py
- notebooks/How to detect branches.ipynb
Hi,
This PR contains a couple of small fixes for the branch detection functionality from my previous PR:
- fix several typo's in the documentation
- use public numpy's API to construct record arrays in the `ApproximationGraph` plotting class.
Kind regards,
Jelmer Bot
> Fix typo's and avoid internal numpy API in branch detection code.

- hdbscan/hdbscan_.py
This will enable interoperability between https://github.com/rapidsai/cuml GPU HDBSCAN implementation and allow us to transfer properties from the GPU model to the CPU model, letting a user train using GPU and predict using CPU.
> Add property setters for class `HDBSCAN`

- setup.py
I've been having trouble build hdbscan on MacOS with normal python (e.g. outside of conda). It turns out that nothing was instructing the build system to actually compile the cython files.
After reading the cython documentation, it seems like the easiest fix is to wrap the extensions list in cythonize(). Locally this built fine.
> Adds cythonize() call to extensions in setup.py()

- hdbscan/branches.py
- hdbscan/plots.py
This PR resolves #668 by silencing numpy's divide by zero warnings for the eccentricity computation. For the ApproximationGraph edge weights, I now divide by 1 / (1 + mutual reachability) instead. This makes the values lie between 0 and 1, which seems more appropriate for graph layout algorithms that use edge weight as a similarity value.
> Silence divide by zero warnings in branch detection code

- README.rst
- docs/how_to_detect_branches.rst
- hdbscan/branches.py
Updates references for the branch-detection arxiv pre-print to the new journal publication.
> branch-detection paper references

- hdbscan/_hdbscan_tree.pyx
- hdbscan/hdbscan_.py
- hdbscan/plots.py
This PR simplifies and optimises the `CondensedTree._select_clusters` and `simplify_hierarchy` functions. It turns out that the `simplify_hierarchy` operation reduces to iterating over the `cluster_tree` in reverse order (so children are processed before their parents).
The PR introduces one behavioural change to `simplify_hierarchy`. Density values are no longer updated when two leaves combine into one. This change ensures that the resulting leaf-combination retains its full density range. Consequently, the resulting simplified tree more accurately reflects the persistence threshold. Only when a leaf merges into a non-leaf are the leaf's density values updated to avoid breaking the condensed tree plot. Those points can have densities higher than the non-leaf's birth density, resulting in …
> simplify_hierarchy and CondensedTree._select_clusters optimisations

- azure-pipelines.yml
Fix `BuildPublishArtifact` CD step for `Manylinux2014Build linux_py312`.
This seems to be related to the issue: https://github.com/scikit-learn-contrib/hdbscan/issues/656
> Fix Build Wheel for Linux python 3.12
